version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ninja-bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      SENTRY_URL: ${SENTRY_URL}
      POSTGRES_URI: ${POSTGRES_URI}
      MIREA_NINJA_GROUP_ID: ${MIREA_NINJA_GROUP_ID}
      YANDEX_API_KEY: ${YANDEX_API_KEY}
      YANDEX_FOLDER_ID: ${YANDEX_FOLDER_ID}
    command: python3 main.py
    restart: always