"""First revision

Revision ID: 322132ed4ca6
Revises: 
Create Date: 2023-01-16 19:59:15.968089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322132ed4ca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('messages', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reputation_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('reputation_delta', sa.FLOAT(), nullable=True),
    sa.Column('force_delta', sa.FLOAT(), nullable=True),
    sa.Column('new_reputation', sa.FLOAT(), nullable=True),
    sa.Column('new_force', sa.FLOAT(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=True),
    sa.Column('first_name', sa.UnicodeText(), nullable=True),
    sa.Column('last_name', sa.UnicodeText(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('reputation', sa.FLOAT(), server_default='0', nullable=False),
    sa.Column('force', sa.FLOAT(), server_default='0', nullable=False),
    sa.Column('update_reputation_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('reputation_updates')
    op.drop_table('messages_history')
    # ### end Alembic commands ###
