"""Create forum integration

Revision ID: 56e14a7595d9
Revises: 322132ed4ca6
Create Date: 2023-01-17 19:48:59.392429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56e14a7595d9'
down_revision = '322132ed4ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages_history', 'chat_id')
    op.add_column('users', sa.Column('discourse_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('discourse_api_key', sa.UnicodeText(), nullable=True))
    op.add_column('users', sa.Column('discourse_notifications_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint(None, 'users', ['discourse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'discourse_notifications_enabled')
    op.drop_column('users', 'discourse_api_key')
    op.drop_column('users', 'discourse_id')
    op.add_column('messages_history', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
