"""Add nonce to user

Revision ID: 6c480b872abf
Revises: 56e14a7595d9
Create Date: 2023-01-17 21:08:33.746678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c480b872abf'
down_revision = '56e14a7595d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discourse_request_nonce', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discourse_request_nonce')
    # ### end Alembic commands ###
